pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/parvathy098/HealthyRecipe.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('HealthyRecipe') {
                    script {
                        sh 'docker build -t parvathykrishna/healthy-recipe:latest .'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir('HealthyRecipe') {
                    script {
                        sh 'npm test'  // Replace with your test framework command
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('HealthyRecipe') {
                    script {
                        // Example: Run Docker to deploy the container
                        sh 'docker run -d -p 3000:3000 parvathykrishna/healthy-recipe:latest'
                    }
                }
            }
        }
    }
}

