pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/parvathy098/HealthyRecipe.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('HealthyRecipe') {
                    script {
                        sh 'docker build -t parvathykrishna/healthy-recipe:latest .'
                    }
                }
            }
        }
        stage('Code Quality Analysis') {
    steps {
        dir('HealthyRecipe') {
            script {
                sh 'sonar-scanner' 
            }
        }
    }
}


        stage('Test') {
            steps {
                dir('HealthyRecipe') {
                    script {
                        sh 'npm test'  // Replace with your test framework command
                    }
                }
            }
        }

        stage('Deploy') {
    steps {
        dir('HealthyRecipe') {
            script {
                // Build and deploy using Docker Compose
                sh 'docker-compose up -d --build'
            }
        }
    }
}

        stage('Release') {
            steps {
                dir('HealthyRecipe') {
                    script {
                        // Push the Docker image to Docker Hub
                        sh 'docker push parvathykrishna/healthy-recipe:latest'
                    }
                }
            }
        }
    }
}

